### ISSUE TITLE
any way, any script. ? 

### ISSUE THREAD

**Issue by glerinsonum** [Gameye98/Black-Hydra#1]
@Gameye98 example.

python get_pass.py -u ( username ) or -i ( id ) -u ( url ) https://www.wordlist.com/wordlist.txt

python get_pass.py -u ( username or -i ( id ) -d ( destination ) facebook.com -p ( port ) 443 

any script for getting password using username or id facebook. 

a deep thanksgiving and gratefully from heart.

**Comment by Gameye98** [comment]
You can try **MBF** from pirmansx repository. For tutorial to use it... you can look for it at youtube
