### ISSUE TITLE
Hydra no existe 

### ISSUE THREAD

**Issue by JesusChapman** [Gameye98/Black-Hydra#11]
hydra no existe y debe ser compilado, yo puedo encargarme de eso, acepte mi solicitud de extracción pronto...

**Comment by kelvin128** [comment]
Hydra not exist on termux

**Comment by JesusChapman** [comment]
Quien dice que no?
Lo compilé, siga estos pasos :

1-suscribase al repositorio comunitario de paquetes termux :  

https://pkgs-yisus.github.io/pkgs.yisus.org/

2- ejecute estos comandos:

pkg install x11-repo
pkg install hydra-dev

Y listo!

**Comment by josuesalomao** [comment]
Hmmmmmmm

**Comment by kokoe-beep** [comment]
> Quien dice que no?
> Lo compilé, siga estos pasos :
> 
> 1-suscribase al repositorio comunitario de paquetes termux :  
> 
> https://pkgs-yisus.github.io/pkgs.yisus.org/
> 
> 2- ejecute estos comandos:
> 
> pkg install x11-repo
> pkg install hydra-dev
> 
> Y listo! 

Ta dando erro no github, falando que não existe >> Está dando un error en github, diciendo que no existe

**Comment by kokoe-beep** [comment]
> Quien dice que no?
> Lo compilé, siga estos pasos :
> 
> 1-suscribase al repositorio comunitario de paquetes termux :  
> 
> https://pkgs-yisus.github.io/pkgs.yisus.org/
> 
> 2- ejecute estos comandos:
> 
> pkg install x11-repo
> pkg install hydra-dev
> 
> Y listo! 

Ta dando erro no github, falando que não existe >> Está dando un error en github, diciendo que no existe

**Comment by JesusChapman** [comment]
> > Quien dice que no?
> > Lo compilé, siga estos pasos :
> > 1-suscribase al repositorio comunitario de paquetes termux :
> > https://pkgs-yisus.github.io/pkgs.yisus.org/
> > 2- ejecute estos comandos:
> > pkg install x11-repo
> > pkg install hydra-dev
> > Y listo!
> 
> Ta dando erro no github, falando que não existe >> Está dando un error en github, diciendo que no existe

Unsustainable project
