### ISSUE TITLE
Error! bruteforce not work

### ISSUE THREAD

**Issue by sasmitadn** [Gameye98/Black-Hydra#3]
Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-11-06 20:14:46
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Google Mail has bruteforce detection and sends false positives. You are not doing anything illegal right?!
[DATA] max 9 tasks per 1 server, overall 9 tasks, 0 login tries (l:9/p:1), ~0 try per task
[DATA] attacking smtp://smtp.gmail.com:25/
[STATUS] 18.00 tries/min, 18 tries in 00:00h, 0 to do in 01:00h, 1 active
1 of 1 target completed, 200000 valid passwords found
[WARNING] Writing restore file because 1 final worker threads did not complete until end.
[ERROR] 1 target did not resolve or could not be connected
[ERROR] 0 targets did not complete
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-11-06 20:16:23

#######
How to fix this? Or my command wrong?

**Comment by Gameye98** [comment]
actually the answer already you provide it by yourself, gmail has bruteforce detection and sends false positives so hydra end the bruteforce session
